// utils/insertuser.js
const fetch = require('node-fetch');

const users = [
        {
        name: 'Urban Company',
        email: 'urbancompany@gmail.com',
        password: 'urbancompany@123',
        role: 'sme',
    },
{
        name: 'Classplus',
        email: 'classplus@gmail.com',
        password: 'classplus@123',
        role: 'vendor',
      },
{
        name: 'Paytm',
        email: 'paytm@gmail.com',
        password: 'paytm@123',
        role: 'vendor',
      },
{
        name: 'Apna',
        email: 'apna@gmail.com',
        password: 'apna@123',
        role: 'sme',
    },
{
        name: 'Razorpay',
        email: 'razorpay@gmail.com',
        password: 'razorpay@123',
        role: 'vendor',
      },
{
        name: 'UpGrad',
        email: 'upgrad@gmail.com',
        password: 'upgrad@123',
        role: 'vendor',
      },
{
        name: 'Delhivery',
        email: 'delhivery@gmail.com',
        password: 'delhivery@123',
        role: 'sme',
    },
{
        name: '1mg',
        email: '1mg@gmail.com',
        password: '1mg@123',
        role: 'vendor',
      },
{
        name: 'BigBasket',
        email: 'bigbasket@gmail.com',
        password: 'bigbasket@123',
        role: 'vendor',
      },
{
        name: 'GoMechanic',
        email: 'gomechanic@gmail.com',
        password: 'gomechanic@123',
        role: 'sme',
    },
{
        name: 'Unacademy',
        email: 'unacademy@gmail.com',
        password: 'unacademy@123',
        role: 'vendor',
      },
{
        name: 'Ola',
        email: 'ola@gmail.com',
        password: 'ola@123',
        role: 'vendor',
      },
{
        name: 'Licious',
        email: 'licious@gmail.com',
        password: 'licious@123',
        role: 'sme',
    },
{
        name: 'CRED',
        email: 'cred@gmail.com',
        password: 'cred@123',
        role: 'vendor',
      },
{
        name: 'CityMall',
        email: 'citymall@gmail.com',
        password: 'citymall@123',
        role: 'vendor',
      },
{
        name: 'Pine Labs',
        email: 'pinelabs@gmail.com',
        password: 'pinelabs@123',
        role: 'sme',
    },
{
        name: 'Dodla Dairy',
        email: 'dodladairy@gmail.com',
        password: 'dodladairy@123',
        role: 'sme',
    },
{
        name: 'Groww',
        email: 'groww@gmail.com',
        password: 'groww@123',
        role: 'sme',
    },
{
        name: 'Grofers',
        email: 'grofers@gmail.com',
        password: 'grofers@123',
        role: 'vendor',
      },
{
        name: 'Jumbotail',
        email: 'jumbotail@gmail.com',
        password: 'jumbotail@123',
        role: 'vendor',
      },
{
        name: 'slice',
        email: 'slice@gmail.com',
        password: 'slice@123',
        role: 'sme',
    },
{
        name: 'InMobi',
        email: 'inmobi@gmail.com',
        password: 'inmobi@123',
        role: 'vendor',
      },
{
        name: 'Dunzo',
        email: 'dunzo@gmail.com',
        password: 'dunzo@123',
        role: 'vendor',
      },
{
        name: 'BYJUâ€™S',
        email: 'byjuâ€™s@gmail.com',
        password: 'byjuâ€™s@123',
        role: 'sme',
    },
{
        name: 'Cashfree',
        email: 'cashfree@gmail.com',
        password: 'cashfree@123',
        role: 'vendor',
      },
{
        name: 'MediBuddy',
        email: 'medibuddy@gmail.com',
        password: 'medibuddy@123',
        role: 'vendor',
      },
{
        name: 'Progcap',
        email: 'progcap@gmail.com',
        password: 'progcap@123',
        role: 'sme',
    },
{
        name: 'Capital Float',
        email: 'capitalfloat@gmail.com',
        password: 'capitalfloat@123',
        role: 'vendor',
      },
{
        name: 'CARS24',
        email: 'cars24@gmail.com',
        password: 'cars24@123',
        role: 'vendor',
      },
{
        name: 'Bharat Biotech',
        email: 'bharatbiotech@gmail.com',
        password: 'bharatbiotech@123',
        role: 'sme',
    },
{
        name: 'Skillmatics',
        email: 'skillmatics@gmail.com',
        password: 'skillmatics@123',
        role: 'vendor',
      },
{
        name: 'Rapido',
        email: 'rapido@gmail.com',
        password: 'rapido@123',
        role: 'vendor',
      },
{
        name: 'Reliance Jio',
        email: 'reliancejio@gmail.com',
        password: 'reliancejio@123',
        role: 'sme',
    },
{
        name: 'YourStory',
        email: 'yourstory@gmail.com',
        password: 'yourstory@123',
        role: 'vendor',
      },
{
        name: 'Kodo',
        email: 'kodo@gmail.com',
        password: 'kodo@123',
        role: 'vendor',
      },
{
        name: 'Practo',
        email: 'practo@gmail.com',
        password: 'practo@123',
        role: 'sme',
    },
{
        name: 'NiYO Solutions',
        email: 'niyosolutions@gmail.com',
        password: 'niyosolutions@123',
        role: 'sme',
    },
{
        name: 'Reliance Retail',
        email: 'relianceretail@gmail.com',
        password: 'relianceretail@123',
        role: 'sme',
    },
{
        name: 'Locus.sh',
        email: 'locus.sh@gmail.com',
        password: 'locus.sh@123',
        role: 'vendor',
      },
{
        name: 'KreditBee',
        email: 'kreditbee@gmail.com',
        password: 'kreditbee@123',
        role: 'vendor',
      },
{
        name: 'boAt',
        email: 'boat@gmail.com',
        password: 'boat@123',
        role: 'sme',
    },
{
        name: 'Flipkart',
        email: 'flipkart@gmail.com',
        password: 'flipkart@123',
        role: 'vendor',
      },
{
        name: 'MobiKwik',
        email: 'mobikwik@gmail.com',
        password: 'mobikwik@123',
        role: 'vendor',
      },
{
        name: 'Cuemath',
        email: 'cuemath@gmail.com',
        password: 'cuemath@123',
        role: 'sme',
    },
{
        name: 'Jai Kisan',
        email: 'jaikisan@gmail.com',
        password: 'jaikisan@123',
        role: 'vendor',
      },
{
        name: 'Infra.Market',
        email: 'infra.market@gmail.com',
        password: 'infra.market@123',
        role: 'vendor',
      },
{
        name: 'Xpressbees',
        email: 'xpressbees@gmail.com',
        password: 'xpressbees@123',
        role: 'sme',
    },
{
        name: 'Northern Arc',
        email: 'northernarc@gmail.com',
        password: 'northernarc@123',
        role: 'vendor',
      },
{
        name: 'Toppr',
        email: 'toppr@gmail.com',
        password: 'toppr@123',
        role: 'vendor',
      },
{
        name: 'MyGlamm',
        email: 'myglamm@gmail.com',
        password: 'myglamm@123',
        role: 'sme',
    },
{
        name: 'ZoomCar',
        email: 'zoomcar@gmail.com',
        password: 'zoomcar@123',
        role: 'vendor',
      },
{
        name: 'Snapdeal',
        email: 'snapdeal@gmail.com',
        password: 'snapdeal@123',
        role: 'vendor',
      },
{
        name: 'WhiteHat Education Technology',
        email: 'whitehateducationtechnology@gmail.com',
        password: 'whitehateducationtechnology@123',
        role: 'sme',
    },
{
        name: 'CarDekho',
        email: 'cardekho@gmail.com',
        password: 'cardekho@123',
        role: 'vendor',
      },
{
        name: 'Koo App',
        email: 'kooapp@gmail.com',
        password: 'kooapp@123',
        role: 'vendor',
      },
{
        name: 'Porter',
        email: 'porter@gmail.com',
        password: 'porter@123',
        role: 'sme',
    },
{
        name: 'Skyroot Aerospace',
        email: 'skyrootaerospace@gmail.com',
        password: 'skyrootaerospace@123',
        role: 'sme',
    },
{
        name: 'Holisol logistics',
        email: 'holisollogistics@gmail.com',
        password: 'holisollogistics@123',
        role: 'sme',
    },
{
        name: 'Exotel',
        email: 'exotel@gmail.com',
        password: 'exotel@123',
        role: 'vendor',
      },
{
        name: 'CarTrade',
        email: 'cartrade@gmail.com',
        password: 'cartrade@123',
        role: 'vendor',
      },
{
        name: 'OPEN',
        email: 'open@gmail.com',
        password: 'open@123',
        role: 'sme',
    },
{
        name: 'InCred',
        email: 'incred@gmail.com',
        password: 'incred@123',
        role: 'vendor',
      },
{
        name: 'Pepperfry',
        email: 'pepperfry@gmail.com',
        password: 'pepperfry@123',
        role: 'vendor',
      },
{
        name: 'Shadowfax',
        email: 'shadowfax@gmail.com',
        password: 'shadowfax@123',
        role: 'sme',
    },
{
        name: 'The Man Company',
        email: 'themancompany@gmail.com',
        password: 'themancompany@123',
        role: 'vendor',
      },
{
        name: 'Agnikul',
        email: 'agnikul@gmail.com',
        password: 'agnikul@123',
        role: 'vendor',
      },
{
        name: 'Shop101',
        email: 'shop101@gmail.com',
        password: 'shop101@123',
        role: 'sme',
    },
{
        name: 'Plum',
        email: 'plum@gmail.com',
        password: 'plum@123',
        role: 'vendor',
      },
{
        name: 'Pee Safe',
        email: 'peesafe@gmail.com',
        password: 'peesafe@123',
        role: 'vendor',
      },
{
        name: 'cure.fit',
        email: 'cure.fit@gmail.com',
        password: 'cure.fit@123',
        role: 'sme',
    },
{
        name: 'Nykaa',
        email: 'nykaa@gmail.com',
        password: 'nykaa@123',
        role: 'vendor',
      },
{
        name: 'NoBroker',
        email: 'nobroker@gmail.com',
        password: 'nobroker@123',
        role: 'vendor',
      },
{
        name: 'PharmEasy',
        email: 'pharmeasy@gmail.com',
        password: 'pharmeasy@123',
        role: 'sme',
    },
{
        name: 'OfBusiness',
        email: 'ofbusiness@gmail.com',
        password: 'ofbusiness@123',
        role: 'vendor',
      },
{
        name: 'LEAD School',
        email: 'leadschool@gmail.com',
        password: 'leadschool@123',
        role: 'vendor',
      },
{
        name: 'Upstox',
        email: 'upstox@gmail.com',
        password: 'upstox@123',
        role: 'sme',
    },
{
        name: 'Teachmint',
        email: 'teachmint@gmail.com',
        password: 'teachmint@123',
        role: 'sme',
    },
{
        name: 'ZestMoney',
        email: 'zestmoney@gmail.com',
        password: 'zestmoney@123',
        role: 'sme',
    },
{
        name: 'Convosight',
        email: 'convosight@gmail.com',
        password: 'convosight@123',
        role: 'vendor',
      },
{
        name: 'Livspace',
        email: 'livspace@gmail.com',
        password: 'livspace@123',
        role: 'vendor',
      },
{
        name: 'Rebel Foods',
        email: 'rebelfoods@gmail.com',
        password: 'rebelfoods@123',
        role: 'sme',
    },
{
        name: 'Spinny',
        email: 'spinny@gmail.com',
        password: 'spinny@123',
        role: 'vendor',
      },
{
        name: 'Synapsica',
        email: 'synapsica@gmail.com',
        password: 'synapsica@123',
        role: 'vendor',
      },
{
        name: 'DeHaat',
        email: 'dehaat@gmail.com',
        password: 'dehaat@123',
        role: 'sme',
    },
{
        name: 'Masai School',
        email: 'masaischool@gmail.com',
        password: 'masaischool@123',
        role: 'vendor',
      },
{
        name: 'Wysa',
        email: 'wysa@gmail.com',
        password: 'wysa@123',
        role: 'vendor',
      },
{
        name: 'Magicpin',
        email: 'magicpin@gmail.com',
        password: 'magicpin@123',
        role: 'sme',
    },
{
        name: 'Ather Energy',
        email: 'atherenergy@gmail.com',
        password: 'atherenergy@123',
        role: 'vendor',
      },
{
        name: 'Trell',
        email: 'trell@gmail.com',
        password: 'trell@123',
        role: 'vendor',
      },
{
        name: 'Convin',
        email: 'convin@gmail.com',
        password: 'convin@123',
        role: 'sme',
    },
{
        name: 'Yellow Messenger',
        email: 'yellowmessenger@gmail.com',
        password: 'yellowmessenger@123',
        role: 'vendor',
      },
{
        name: 'Mamaearth',
        email: 'mamaearth@gmail.com',
        password: 'mamaearth@123',
        role: 'vendor',
      },
{
        name: 'Milkbasket',
        email: 'milkbasket@gmail.com',
        password: 'milkbasket@123',
        role: 'sme',
    },
{
        name: 'Bimaplan',
        email: 'bimaplan@gmail.com',
        password: 'bimaplan@123',
        role: 'vendor',
      },
{
        name: 'Urban Ladder',
        email: 'urbanladder@gmail.com',
        password: 'urbanladder@123',
        role: 'vendor',
      },
{
        name: 'PagarBook',
        email: 'pagarbook@gmail.com',
        password: 'pagarbook@123',
        role: 'sme',
    },
{
        name: 'Paytm Payments Bank',
        email: 'paytmpaymentsbank@gmail.com',
        password: 'paytmpaymentsbank@123',
        role: 'sme',
    },
{
        name: 'OkCredit',
        email: 'okcredit@gmail.com',
        password: 'okcredit@123',
        role: 'sme',
    },
{
        name: 'Purplle',
        email: 'purplle@gmail.com',
        password: 'purplle@123',
        role: 'vendor',
      },
{
        name: 'MyMoneyMantra',
        email: 'mymoneymantra@gmail.com',
        password: 'mymoneymantra@123',
        role: 'vendor',
      },
{
        name: 'Blackbuck',
        email: 'blackbuck@gmail.com',
        password: 'blackbuck@123',
        role: 'sme',
    },
{
        name: 'Wakefit',
        email: 'wakefit@gmail.com',
        password: 'wakefit@123',
        role: 'vendor',
      },
{
        name: 'Freshtohome',
        email: 'freshtohome@gmail.com',
        password: 'freshtohome@123',
        role: 'vendor',
      },
{
        name: 'Housing.com',
        email: 'housing.com@gmail.com',
        password: 'housing.com@123',
        role: 'sme',
    },
{
        name: 'Doubtnut',
        email: 'doubtnut@gmail.com',
        password: 'doubtnut@123',
        role: 'vendor',
      },
{
        name: 'smallcase',
        email: 'smallcase@gmail.com',
        password: 'smallcase@123',
        role: 'vendor',
      },
{
        name: 'Instamojo',
        email: 'instamojo@gmail.com',
        password: 'instamojo@123',
        role: 'sme',
    },
{
        name: 'Zomato',
        email: 'zomato@gmail.com',
        password: 'zomato@123',
        role: 'vendor',
      },
{
        name: 'SUGAR Cosmetics',
        email: 'sugarcosmetics@gmail.com',
        password: 'sugarcosmetics@123',
        role: 'vendor',
      },
{
        name: 'WinZO',
        email: 'winzo@gmail.com',
        password: 'winzo@123',
        role: 'sme',
    },
{
        name: 'Chingari',
        email: 'chingari@gmail.com',
        password: 'chingari@123',
        role: 'vendor',
      },
{
        name: 'Fisdom',
        email: 'fisdom@gmail.com',
        password: 'fisdom@123',
        role: 'vendor',
      },
{
        name: 'Digit Insurance',
        email: 'digitinsurance@gmail.com',
        password: 'digitinsurance@123',
        role: 'sme',
    },
{
        name: 'Aye Finance',
        email: 'ayefinance@gmail.com',
        password: 'ayefinance@123',
        role: 'vendor',
      },
{
        name: 'Rivigo',
        email: 'rivigo@gmail.com',
        password: 'rivigo@123',
        role: 'vendor',
      },
{
        name: 'Pepper Content',
        email: 'peppercontent@gmail.com',
        password: 'peppercontent@123',
        role: 'sme',
    },
{
        name: 'Get My Parking',
        email: 'getmyparking@gmail.com',
        password: 'getmyparking@123',
        role: 'sme',
    },
{
        name: 'FabAlley',
        email: 'faballey@gmail.com',
        password: 'faballey@123',
        role: 'sme',
    },
{
        name: 'FarMart',
        email: 'farmart@gmail.com',
        password: 'farmart@123',
        role: 'vendor',
      },
{
        name: 'mfine',
        email: 'mfine@gmail.com',
        password: 'mfine@123',
        role: 'vendor',
      },
{
        name: 'Medlife',
        email: 'medlife@gmail.com',
        password: 'medlife@123',
        role: 'sme',
    },
{
        name: 'Lendingkart',
        email: 'lendingkart@gmail.com',
        password: 'lendingkart@123',
        role: 'vendor',
      },
{
        name: 'Chqbook',
        email: 'chqbook@gmail.com',
        password: 'chqbook@123',
        role: 'vendor',
      },
{
        name: 'Turtlemint',
        email: 'turtlemint@gmail.com',
        password: 'turtlemint@123',
        role: 'sme',
    },
{
        name: 'Ecom Express',
        email: 'ecomexpress@gmail.com',
        password: 'ecomexpress@123',
        role: 'vendor',
      },
{
        name: 'BharatPe',
        email: 'bharatpe@gmail.com',
        password: 'bharatpe@123',
        role: 'vendor',
      },
{
        name: 'Vymo',
        email: 'vymo@gmail.com',
        password: 'vymo@123',
        role: 'sme',
    },
{
        name: 'Shiprocket',
        email: 'shiprocket@gmail.com',
        password: 'shiprocket@123',
        role: 'vendor',
      },
{
        name: 'LeadSquared',
        email: 'leadsquared@gmail.com',
        password: 'leadsquared@123',
        role: 'vendor',
      },
{
        name: 'FamPay',
        email: 'fampay@gmail.com',
        password: 'fampay@123',
        role: 'sme',
    },
{
        name: 'Quikr',
        email: 'quikr@gmail.com',
        password: 'quikr@123',
        role: 'vendor',
      },
{
        name: 'Quizizz',
        email: 'quizizz@gmail.com',
        password: 'quizizz@123',
        role: 'vendor',
      },
{
        name: 'Stanza Living',
        email: 'stanzaliving@gmail.com',
        password: 'stanzaliving@123',
        role: 'sme',
    },
{
        name: 'Pristyn Care',
        email: 'pristyncare@gmail.com',
        password: 'pristyncare@123',
        role: 'vendor',
      },
{
        name: 'Polygon (Previously Matic Network)',
        email: 'polygon(previouslymaticnetwork)@gmail.com',
        password: 'polygon(previouslymaticnetwork)@123',
        role: 'vendor',
      },
{
        name: 'Bobble AI',
        email: 'bobbleai@gmail.com',
        password: 'bobbleai@123',
        role: 'sme',
    },
{
        name: 'Cell Propulsion',
        email: 'cellpropulsion@gmail.com',
        password: 'cellpropulsion@123',
        role: 'sme',
    },
{
        name: 'DukaanÂ®',
        email: 'dukaanâ®@gmail.com',
        password: 'dukaanâ®@123',
        role: 'sme',
    },
{
        name: 'Play Shifu',
        email: 'playshifu@gmail.com',
        password: 'playshifu@123',
        role: 'vendor',
      },
{
        name: 'Lava International Limited',
        email: 'lavainternationallimited@gmail.com',
        password: 'lavainternationallimited@123',
        role: 'vendor',
      },
{
        name: 'Vivriti Capital',
        email: 'vivriticapital@gmail.com',
        password: 'vivriticapital@123',
        role: 'sme',
    },
{
        name: 'DocsApp',
        email: 'docsapp@gmail.com',
        password: 'docsapp@123',
        role: 'vendor',
      },
{
        name: 'Furlenco',
        email: 'furlenco@gmail.com',
        password: 'furlenco@123',
        role: 'vendor',
      },
{
        name: 'Swiggy',
        email: 'swiggy@gmail.com',
        password: 'swiggy@123',
        role: 'sme',
    },
{
        name: 'Bombay Shaving Company',
        email: 'bombayshavingcompany@gmail.com',
        password: 'bombayshavingcompany@123',
        role: 'vendor',
      },
{
        name: 'Treebo Hotels',
        email: 'treebohotels@gmail.com',
        password: 'treebohotels@123',
        role: 'vendor',
      },
{
        name: 'Betterhalf',
        email: 'betterhalf@gmail.com',
        password: 'betterhalf@123',
        role: 'sme',
    },
{
        name: 'JioSaavn',
        email: 'jiosaavn@gmail.com',
        password: 'jiosaavn@123',
        role: 'vendor',
      },
{
        name: 'nearbuy',
        email: 'nearbuy@gmail.com',
        password: 'nearbuy@123',
        role: 'vendor',
      },
{
        name: 'Indifi Technologies',
        email: 'indifitechnologies@gmail.com',
        password: 'indifitechnologies@123',
        role: 'sme',
    },
{
        name: 'Portea Medical',
        email: 'porteamedical@gmail.com',
        password: 'porteamedical@123',
        role: 'vendor',
      },
{
        name: 'Stashfin',
        email: 'stashfin@gmail.com',
        password: 'stashfin@123',
        role: 'vendor',
      },
{
        name: 'Square Yards',
        email: 'squareyards@gmail.com',
        password: 'squareyards@123',
        role: 'sme',
    },
{
        name: 'HealthifyMe',
        email: 'healthifyme@gmail.com',
        password: 'healthifyme@123',
        role: 'vendor',
      },
{
        name: 'QuickSell',
        email: 'quicksell@gmail.com',
        password: 'quicksell@123',
        role: 'vendor',
      },
{
        name: 'Perpule',
        email: 'perpule@gmail.com',
        password: 'perpule@123',
        role: 'sme',
    },
{
        name: 'ReNew Power',
        email: 'renewpower@gmail.com',
        password: 'renewpower@123',
        role: 'sme',
    },
{
        name: 'Hike',
        email: 'hike@gmail.com',
        password: 'hike@123',
        role: 'sme',
    },
{
        name: 'Mswipe Technologies',
        email: 'mswipetechnologies@gmail.com',
        password: 'mswipetechnologies@123',
        role: 'vendor',
      },
{
        name: 'Virohan',
        email: 'virohan@gmail.com',
        password: 'virohan@123',
        role: 'vendor',
      },
{
        name: 'BimaPe',
        email: 'bimape@gmail.com',
        password: 'bimape@123',
        role: 'sme',
    },
{
        name: 'Netmeds',
        email: 'netmeds@gmail.com',
        password: 'netmeds@123',
        role: 'vendor',
      },
{
        name: 'XYXX Apparels',
        email: 'xyxxapparels@gmail.com',
        password: 'xyxxapparels@123',
        role: 'vendor',
      },
{
        name: 'One97',
        email: 'one97@gmail.com',
        password: 'one97@123',
        role: 'sme',
    },
{
        name: 'Airmeet',
        email: 'airmeet@gmail.com',
        password: 'airmeet@123',
        role: 'vendor',
      },
{
        name: 'BookMyShow',
        email: 'bookmyshow@gmail.com',
        password: 'bookmyshow@123',
        role: 'vendor',
      },
{
        name: 'Embibe',
        email: 'embibe@gmail.com',
        password: 'embibe@123',
        role: 'sme',
    },
{
        name: 'Awign Enterprises',
        email: 'awignenterprises@gmail.com',
        password: 'awignenterprises@123',
        role: 'vendor',
      },
{
        name: 'ixigo',
        email: 'ixigo@gmail.com',
        password: 'ixigo@123',
        role: 'vendor',
      },
{
        name: 'Shuttl',
        email: 'shuttl@gmail.com',
        password: 'shuttl@123',
        role: 'sme',
    },
{
        name: 'Chai Point',
        email: 'chaipoint@gmail.com',
        password: 'chaipoint@123',
        role: 'vendor',
      },
{
        name: 'Avail Finance',
        email: 'availfinance@gmail.com',
        password: 'availfinance@123',
        role: 'vendor',
      },
{
        name: 'Flock',
        email: 'flock@gmail.com',
        password: 'flock@123',
        role: 'sme',
    },
{
        name: 'GlowRoad',
        email: 'glowroad@gmail.com',
        password: 'glowroad@123',
        role: 'vendor',
      },
{
        name: 'HomeLane',
        email: 'homelane@gmail.com',
        password: 'homelane@123',
        role: 'vendor',
      },
{
        name: 'Wow! Momo',
        email: 'wow!momo@gmail.com',
        password: 'wow!momo@123',
        role: 'sme',
    },
{
        name: 'LetsTransport',
        email: 'letstransport@gmail.com',
        password: 'letstransport@123',
        role: 'sme',
    },
{
        name: 'Digital Class E-Learning Marketplace',
        email: 'digitalclasse-learningmarketplace@gmail.com',
        password: 'digitalclasse-learningmarketplace@123',
        role: 'sme',
    },
{
        name: 'RentoMojo',
        email: 'rentomojo@gmail.com',
        password: 'rentomojo@123',
        role: 'vendor',
      },
{
        name: 'SBI Life',
        email: 'sbilife@gmail.com',
        password: 'sbilife@123',
        role: 'vendor',
      },
{
        name: 'Zivame.com',
        email: 'zivame.com@gmail.com',
        password: 'zivame.com@123',
        role: 'sme',
    },
{
        name: 'VerSe Innovation',
        email: 'verseinnovation@gmail.com',
        password: 'verseinnovation@123',
        role: 'vendor',
      },
{
        name: 'CoinDCX',
        email: 'coindcx@gmail.com',
        password: 'coindcx@123',
        role: 'vendor',
      },
{
        name: 'Country Delight',
        email: 'countrydelight@gmail.com',
        password: 'countrydelight@123',
        role: 'sme',
    },
{
        name: 'BankBazaar.com',
        email: 'bankbazaar.com@gmail.com',
        password: 'bankbazaar.com@123',
        role: 'vendor',
      },
{
        name: 'Happay',
        email: 'happay@gmail.com',
        password: 'happay@123',
        role: 'vendor',
      },
{
        name: 'Five Star Business Finance',
        email: 'fivestarbusinessfinance@gmail.com',
        password: 'fivestarbusinessfinance@123',
        role: 'sme',
    },
{
        name: 'Goodera',
        email: 'goodera@gmail.com',
        password: 'goodera@123',
        role: 'vendor',
      },
{
        name: 'Simpl',
        email: 'simpl@gmail.com',
        password: 'simpl@123',
        role: 'vendor',
      },
{
        name: 'F5 Refreshement',
        email: 'f5refreshement@gmail.com',
        password: 'f5refreshement@123',
        role: 'sme',
    },
{
        name: 'ShopClues',
        email: 'shopclues@gmail.com',
        password: 'shopclues@123',
        role: 'vendor',
      },
{
        name: 'Aknamed',
        email: 'aknamed@gmail.com',
        password: 'aknamed@123',
        role: 'vendor',
      },
{
        name: 'Droom',
        email: 'droom@gmail.com',
        password: 'droom@123',
        role: 'sme',
    },
{
        name: 'Box8',
        email: 'box8@gmail.com',
        password: 'box8@123',
        role: 'vendor',
      },
{
        name: 'Cashkaro',
        email: 'cashkaro@gmail.com',
        password: 'cashkaro@123',
        role: 'vendor',
      },
{
        name: 'CropIn',
        email: 'cropin@gmail.com',
        password: 'cropin@123',
        role: 'sme',
    },
{
        name: 'Jupiter',
        email: 'jupiter@gmail.com',
        password: 'jupiter@123',
        role: 'sme',
    },
{
        name: 'ShopX',
        email: 'shopx@gmail.com',
        password: 'shopx@123',
        role: 'sme',
    },
{
        name: 'LocoNav',
        email: 'loconav@gmail.com',
        password: 'loconav@123',
        role: 'vendor',
      },
{
        name: 'Avataar.Me',
        email: 'avataar.me@gmail.com',
        password: 'avataar.me@123',
        role: 'vendor',
      },
{
        name: 'BluSmart Mobility',
        email: 'blusmartmobility@gmail.com',
        password: 'blusmartmobility@123',
        role: 'sme',
    },
{
        name: 'SleepyCat',
        email: 'sleepycat@gmail.com',
        password: 'sleepycat@123',
        role: 'vendor',
      },
{
        name: 'INDwealth',
        email: 'indwealth@gmail.com',
        password: 'indwealth@123',
        role: 'vendor',
      },
{
        name: 'Shipsy',
        email: 'shipsy@gmail.com',
        password: 'shipsy@123',
        role: 'sme',
    },
{
        name: 'Kissht',
        email: 'kissht@gmail.com',
        password: 'kissht@123',
        role: 'vendor',
      },
{
        name: 'MedGenome',
        email: 'medgenome@gmail.com',
        password: 'medgenome@123',
        role: 'vendor',
      },
{
        name: 'Fabhotels',
        email: 'fabhotels@gmail.com',
        password: 'fabhotels@123',
        role: 'sme',
    },
{
        name: 'Loadshare',
        email: 'loadshare@gmail.com',
        password: 'loadshare@123',
        role: 'vendor',
      },
{
        name: 'Gradeup',
        email: 'gradeup@gmail.com',
        password: 'gradeup@123',
        role: 'vendor',
      },
{
        name: 'FreeCharge',
        email: 'freecharge@gmail.com',
        password: 'freecharge@123',
        role: 'sme',
    },
{
        name: 'Healthkart',
        email: 'healthkart@gmail.com',
        password: 'healthkart@123',
        role: 'vendor',
      },
{
        name: 'Saveo',
        email: 'saveo@gmail.com',
        password: 'saveo@123',
        role: 'vendor',
      },
{
        name: 'True Balance',
        email: 'truebalance@gmail.com',
        password: 'truebalance@123',
        role: 'sme',
    },
{
        name: 'Coverfox Insurance',
        email: 'coverfoxinsurance@gmail.com',
        password: 'coverfoxinsurance@123',
        role: 'vendor',
      },
{
        name: 'EarlySalary',
        email: 'earlysalary@gmail.com',
        password: 'earlysalary@123',
        role: 'vendor',
      },
{
        name: 'Pitstop',
        email: 'pitstop@gmail.com',
        password: 'pitstop@123',
        role: 'sme',
    },
{
        name: 'Wheels Eye',
        email: 'wheelseye@gmail.com',
        password: 'wheelseye@123',
        role: 'sme',
    },
{
        name: 'Bira 91',
        email: 'bira91@gmail.com',
        password: 'bira91@123',
        role: 'sme',
    },
{
        name: 'PlanetSpark',
        email: 'planetspark@gmail.com',
        password: 'planetspark@123',
        role: 'vendor',
      },
{
        name: 'LimeRoad',
        email: 'limeroad@gmail.com',
        password: 'limeroad@123',
        role: 'vendor',
      },
{
        name: 'Pratilipi',
        email: 'pratilipi@gmail.com',
        password: 'pratilipi@123',
        role: 'sme',
    },
{
        name: 'Freight Tiger',
        email: 'freighttiger@gmail.com',
        password: 'freighttiger@123',
        role: 'vendor',
      },
{
        name: 'unlu',
        email: 'unlu@gmail.com',
        password: 'unlu@123',
        role: 'vendor',
      },
{
        name: 'KIMS Hospitals',
        email: 'kimshospitals@gmail.com',
        password: 'kimshospitals@123',
        role: 'sme',
    },
{
        name: 'InterviewBit',
        email: 'interviewbit@gmail.com',
        password: 'interviewbit@123',
        role: 'vendor',
      },
{
        name: 'Oye Rickshaw',
        email: 'oyerickshaw@gmail.com',
        password: 'oyerickshaw@123',
        role: 'vendor',
      },
{
        name: 'Arzooo.com',
        email: 'arzooo.com@gmail.com',
        password: 'arzooo.com@123',
        role: 'sme',
    },
{
        name: 'Amber Group',
        email: 'ambergroup@gmail.com',
        password: 'ambergroup@123',
        role: 'vendor',
      },
{
        name: 'Star Health and Allied Insurance',
        email: 'starhealthandalliedinsurance@gmail.com',
        password: 'starhealthandalliedinsurance@123',
        role: 'vendor',
      },
{
        name: 'Magicbricks',
        email: 'magicbricks@gmail.com',
        password: 'magicbricks@123',
        role: 'sme',
    },
{
        name: 'Unbxd',
        email: 'unbxd@gmail.com',
        password: 'unbxd@123',
        role: 'vendor',
      },
{
        name: 'LIDO',
        email: 'lido@gmail.com',
        password: 'lido@123',
        role: 'vendor',
      },
{
        name: 'Yulu',
        email: 'yulu@gmail.com',
        password: 'yulu@123',
        role: 'sme',
    },
{
        name: 'Cashify',
        email: 'cashify@gmail.com',
        password: 'cashify@123',
        role: 'vendor',
      },
{
        name: 'Revv',
        email: 'revv@gmail.com',
        password: 'revv@123',
        role: 'vendor',
      },
{
        name: 'UrbanPiper',
        email: 'urbanpiper@gmail.com',
        password: 'urbanpiper@123',
        role: 'sme',
    },
{
        name: 'PropTiger',
        email: 'proptiger@gmail.com',
        password: 'proptiger@123',
        role: 'sme',
    },
{
        name: 'Miko',
        email: 'miko@gmail.com',
        password: 'miko@123',
        role: 'sme',
    },
{
        name: 'HungerBox',
        email: 'hungerbox@gmail.com',
        password: 'hungerbox@123',
        role: 'vendor',
      },
{
        name: 'OYO',
        email: 'oyo@gmail.com',
        password: 'oyo@123',
        role: 'vendor',
      },
{
        name: 'Leap Finance',
        email: 'leapfinance@gmail.com',
        password: 'leapfinance@123',
        role: 'sme',
    },
{
        name: 'MedPlus',
        email: 'medplus@gmail.com',
        password: 'medplus@123',
        role: 'vendor',
      },
{
        name: 'PiggyRide',
        email: 'piggyride@gmail.com',
        password: 'piggyride@123',
        role: 'vendor',
      },
{
        name: 'Vernacular.ai',
        email: 'vernacular.ai@gmail.com',
        password: 'vernacular.ai@123',
        role: 'sme',
    },
{
        name: 'ShareChat',
        email: 'sharechat@gmail.com',
        password: 'sharechat@123',
        role: 'vendor',
      },
{
        name: 'PhableCare',
        email: 'phablecare@gmail.com',
        password: 'phablecare@123',
        role: 'vendor',
      },
{
        name: 'OZiva',
        email: 'oziva@gmail.com',
        password: 'oziva@123',
        role: 'sme',
    },
{
        name: 'Testbook.com',
        email: 'testbook.com@gmail.com',
        password: 'testbook.com@123',
        role: 'vendor',
      },
{
        name: 'Billdesk',
        email: 'billdesk@gmail.com',
        password: 'billdesk@123',
        role: 'vendor',
      },
{
        name: 'Flatheads',
        email: 'flatheads@gmail.com',
        password: 'flatheads@123',
        role: 'sme',
    },
{
        name: 'Signzy',
        email: 'signzy@gmail.com',
        password: 'signzy@123',
        role: 'vendor',
      },
{
        name: 'RAW Pressery',
        email: 'rawpressery@gmail.com',
        password: 'rawpressery@123',
        role: 'vendor',
      },
{
        name: 'WorkIndia',
        email: 'workindia@gmail.com',
        password: 'workindia@123',
        role: 'sme',
    },
{
        name: 'WebEngage',
        email: 'webengage@gmail.com',
        password: 'webengage@123',
        role: 'vendor',
      },
{
        name: 'Chumbak',
        email: 'chumbak@gmail.com',
        password: 'chumbak@123',
        role: 'vendor',
      },
{
        name: 'Mu Sigma',
        email: 'musigma@gmail.com',
        password: 'musigma@123',
        role: 'sme',
    },
{
        name: 'Myelin Foundry',
        email: 'myelinfoundry@gmail.com',
        password: 'myelinfoundry@123',
        role: 'sme',
    },
{
        name: 'JUSPAY',
        email: 'juspay@gmail.com',
        password: 'juspay@123',
        role: 'sme',
    },
{
        name: 'DaMENSCH',
        email: 'damensch@gmail.com',
        password: 'damensch@123',
        role: 'vendor',
      },
{
        name: 'InstantPay',
        email: 'instantpay@gmail.com',
        password: 'instantpay@123',
        role: 'vendor',
      },
{
        name: 'ITILITE',
        email: 'itilite@gmail.com',
        password: 'itilite@123',
        role: 'sme',
    },
{
        name: 'Fyle',
        email: 'fyle@gmail.com',
        password: 'fyle@123',
        role: 'vendor',
      },
{
        name: 'Trulymadly.com',
        email: 'trulymadly.com@gmail.com',
        password: 'trulymadly.com@123',
        role: 'vendor',
      },
{
        name: 'Quess Corp',
        email: 'quesscorp@gmail.com',
        password: 'quesscorp@123',
        role: 'sme',
    },
{
        name: 'FreshMenu',
        email: 'freshmenu@gmail.com',
        password: 'freshmenu@123',
        role: 'vendor',
      },
{
        name: 'NODWIN Gaming',
        email: 'nodwingaming@gmail.com',
        password: 'nodwingaming@123',
        role: 'vendor',
      },
{
        name: 'IDfy',
        email: 'idfy@gmail.com',
        password: 'idfy@123',
        role: 'sme',
    },
{
        name: 'Kinara Capital',
        email: 'kinaracapital@gmail.com',
        password: 'kinaracapital@123',
        role: 'vendor',
      },
{
        name: 'Niki',
        email: 'niki@gmail.com',
        password: 'niki@123',
        role: 'vendor',
      },
{
        name: 'MyGate',
        email: 'mygate@gmail.com',
        password: 'mygate@123',
        role: 'sme',
    },
{
        name: 'Neogrowth',
        email: 'neogrowth@gmail.com',
        password: 'neogrowth@123',
        role: 'vendor',
      },
{
        name: 'Paytm Mall',
        email: 'paytmmall@gmail.com',
        password: 'paytmmall@123',
        role: 'vendor',
      },
{
        name: 'Hopscotch',
        email: 'hopscotch@gmail.com',
        password: 'hopscotch@123',
        role: 'sme',
    },
{
        name: 'Setu',
        email: 'setu@gmail.com',
        password: 'setu@123',
        role: 'vendor',
      },
{
        name: 'Blue Tokai Coffee Roasters',
        email: 'bluetokaicoffeeroasters@gmail.com',
        password: 'bluetokaicoffeeroasters@123',
        role: 'vendor',
      },
{
        name: 'Avanse Financial Services',
        email: 'avansefinancialservices@gmail.com',
        password: 'avansefinancialservices@123',
        role: 'sme',
    },
{
        name: 'Gaana',
        email: 'gaana@gmail.com',
        password: 'gaana@123',
        role: 'sme',
    },
{
        name: 'LiquiLoans',
        email: 'liquiloans@gmail.com',
        password: 'liquiloans@123',
        role: 'sme',
    },
{
        name: 'Clovia',
        email: 'clovia@gmail.com',
        password: 'clovia@123',
        role: 'vendor',
      },
{
        name: 'Scripbox',
        email: 'scripbox@gmail.com',
        password: 'scripbox@123',
        role: 'vendor',
      },
{
        name: 'RateGain',
        email: 'rategain@gmail.com',
        password: 'rategain@123',
        role: 'sme',
    },
{
        name: 'Epigamia',
        email: 'epigamia@gmail.com',
        password: 'epigamia@123',
        role: 'vendor',
      },
{
        name: 'MCaffeine',
        email: 'mcaffeine@gmail.com',
        password: 'mcaffeine@123',
        role: 'vendor',
      },
{
        name: 'Chaayos',
        email: 'chaayos@gmail.com',
        password: 'chaayos@123',
        role: 'sme',
    },
{
        name: 'TVF',
        email: 'tvf@gmail.com',
        password: 'tvf@123',
        role: 'vendor',
      },
{
        name: 'WOW Skin Science India Ltd',
        email: 'wowskinscienceindialtd@gmail.com',
        password: 'wowskinscienceindialtd@123',
        role: 'vendor',
      },
{
        name: 'Financial Software & Systems',
        email: 'financialsoftware&systems@gmail.com',
        password: 'financialsoftware&systems@123',
        role: 'sme',
    },
{
        name: 'Ezetap',
        email: 'ezetap@gmail.com',
        password: 'ezetap@123',
        role: 'vendor',
      },
{
        name: 'Financepeer',
        email: 'financepeer@gmail.com',
        password: 'financepeer@123',
        role: 'vendor',
      },
{
        name: 'Haptik',
        email: 'haptik@gmail.com',
        password: 'haptik@123',
        role: 'sme',
    },
{
        name: 'GirnarSoft',
        email: 'girnarsoft@gmail.com',
        password: 'girnarsoft@123',
        role: 'vendor',
      },
{
        name: 'Meesho',
        email: 'meesho@gmail.com',
        password: 'meesho@123',
        role: 'vendor',
      },
{
        name: 'Lenskart',
        email: 'lenskart@gmail.com',
        password: 'lenskart@123',
        role: 'sme',
    },
{
        name: 'Udaan',
        email: 'udaan@gmail.com',
        password: 'udaan@123',
        role: 'vendor',
      },
{
        name: 'Zolve',
        email: 'zolve@gmail.com',
        password: 'zolve@123',
        role: 'vendor',
      },
{
        name: 'SafexPay',
        email: 'safexpay@gmail.com',
        password: 'safexpay@123',
        role: 'sme',
    },
{
        name: 'Pariksha',
        email: 'pariksha@gmail.com',
        password: 'pariksha@123',
        role: 'sme',
    },
{
        name: 'Fyllo',
        email: 'fyllo@gmail.com',
        password: 'fyllo@123',
        role: 'sme',
    },
{
        name: 'CredFlow',
        email: 'credflow@gmail.com',
        password: 'credflow@123',
        role: 'vendor',
      },
{
        name: 'HalaPlay Technologies',
        email: 'halaplaytechnologies@gmail.com',
        password: 'halaplaytechnologies@123',
        role: 'vendor',
      },

    ];

async function insertUsers() {
  for (const user of users) {
    try {
      const res = await fetch("http://localhost:5000/api/admin/upsert-user", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json"
        },
        body: JSON.stringify(user)
      });

      const data = await res.json();

      if (res.ok) {
        console.log(`✅ ${user.email}: ${data.message}`);
      } else {
        console.error(`❌ ${user.email}: ${data.message || "Unknown error"}`);
      }
    } catch (err) {
      console.error(`❌ Exception for ${user.email}:`, err.message);
    }
  }
}

insertUsers();
